//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventParkering.Language {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("EventParkering.Language.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string FindLabelResx {
            get {
                return ResourceManager.GetString("FindLabelResx", resourceCulture);
            }
        }
        
        internal static string ParkLabelResx {
            get {
                return ResourceManager.GetString("ParkLabelResx", resourceCulture);
            }
        }
        
        internal static string VersionLabelResx {
            get {
                return ResourceManager.GetString("VersionLabelResx", resourceCulture);
            }
        }
        
        internal static string InfoLabelResx {
            get {
                return ResourceManager.GetString("InfoLabelResx", resourceCulture);
            }
        }
        
        internal static string TryLabelResx {
            get {
                return ResourceManager.GetString("TryLabelResx", resourceCulture);
            }
        }
        
        internal static string KnowMoreLabelResx {
            get {
                return ResourceManager.GetString("KnowMoreLabelResx", resourceCulture);
            }
        }
        
        internal static string HelloLabelResx {
            get {
                return ResourceManager.GetString("HelloLabelResx", resourceCulture);
            }
        }
        
        internal static string WhereGoLabelResx {
            get {
                return ResourceManager.GetString("WhereGoLabelResx", resourceCulture);
            }
        }
        
        internal static string DrivelabelResx {
            get {
                return ResourceManager.GetString("DrivelabelResx", resourceCulture);
            }
        }
        
        internal static string ChooseLabelResx {
            get {
                return ResourceManager.GetString("ChooseLabelResx", resourceCulture);
            }
        }
        
        internal static string ClosestLabelResx {
            get {
                return ResourceManager.GetString("ClosestLabelResx", resourceCulture);
            }
        }
        
        internal static string ParkingSpotLabelResx {
            get {
                return ResourceManager.GetString("ParkingSpotLabelResx", resourceCulture);
            }
        }
        
        internal static string MapShowsLabelResx {
            get {
                return ResourceManager.GetString("MapShowsLabelResx", resourceCulture);
            }
        }
        
        internal static string AddressLabelResx {
            get {
                return ResourceManager.GetString("AddressLabelResx", resourceCulture);
            }
        }
        
        internal static string TitleLabelResx {
            get {
                return ResourceManager.GetString("TitleLabelResx", resourceCulture);
            }
        }
    }
}
